In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [2]:
pwd

'/content'

In [3]:
import keras
from keras.datasets import fashion_mnist

import numpy as np
from PIL import Image, ImageOps
import os

In [4]:
# to change every_folder with label  

code = {'Tshirt':0 ,'Trouser':1,'Pullover':2,'Dress':3,'Coat':4,'Sandal':5,'Shirt':6,'Sneaker':7,'Bag':8,'Ankle boot':9}
#######################
def getcode(n) : 
    for x , y in code.items() : 
        if n == y : 
            return x

In [5]:
def save_image(filename, data_array):
    im = Image.fromarray(data_array.astype('uint8'))
    im_invert = ImageOps.invert(im)
    im_invert.save(filename)

# Load Fashion-MNIST Data
(x_train, y_train), (x_test, y_test) = fashion_mnist.load_data()

DIR_NAME = "data/train/Tshirt"
if os.path.exists(DIR_NAME) == False:
    os.mkdir(DIR_NAME)
DIR_NAME = "data/train/Trouser"
if os.path.exists(DIR_NAME) == False:
    os.mkdir(DIR_NAME)
DIR_NAME = "data/train/Dress"
if os.path.exists(DIR_NAME) == False:
    os.mkdir(DIR_NAME)
DIR_NAME = "data/train/Coat"
if os.path.exists(DIR_NAME) == False:
    os.mkdir(DIR_NAME)
DIR_NAME = "data/train/Sandal"
if os.path.exists(DIR_NAME) == False:
    os.mkdir(DIR_NAME)
DIR_NAME = "data/train/Shirt"
if os.path.exists(DIR_NAME) == False:
    os.mkdir(DIR_NAME)
DIR_NAME = "data/train/Sneaker"
if os.path.exists(DIR_NAME) == False:
    os.mkdir(DIR_NAME)
DIR_NAME = "data/train/Ankle boot"    
if os.path.exists(DIR_NAME) == False:
    os.mkdir(DIR_NAME)
DIR_NAME = "data/train/Bag"  
if os.path.exists(DIR_NAME) == False:
    os.mkdir(DIR_NAME)
DIR_NAME = "data/train/Pullover"  
if os.path.exists(DIR_NAME) == False:
    os.mkdir(DIR_NAME)

# Save Images
i = 0
for li in [x_train]:
    print("[---------------------------------------------------------------]")
    for x in li:
        name = getcode(y_train[i])
        if name == "Tshirt" :
            filename = "data/train/Tshirt/{0}.jpg".format(i)
        elif name == "Trouser" :
            filename = "data/train/Trouser/{0}.jpg".format(i)
        elif name == "Dress" :
            filename = "data/train/Dress/{0}.jpg".format(i)
        elif name == "Coat" :
            filename = "data/train/Coat/{0}.jpg".format(i)
        elif name == "Sandal" :
            filename = "data/train/Sandal/{0}.jpg".format(i)
        elif name == "Shirt" :
            filename = "data/train/Shirt/{0}.jpg".format(i)
        elif name == "Sneaker" :
            filename = "data/train/Sneaker/{0}.jpg".format(i)
        elif name == "Bag" :
            filename = "data/train/Bag/{0}.jpg".format(i)
        elif name == "Ankle boot" :
            filename = "data/train/Ankle boot/{0}.jpg".format(i)
        elif name == "Pullover" :
            filename = "data/train/Pullover/{0}.jpg".format(i)
        print(filename)
        save_image(filename, x)
        i += 1

Streaming output truncated to the last 5000 lines.
data/train/Tshirt/55000.jpg
data/train/Bag/55001.jpg
data/train/Tshirt/55002.jpg
data/train/Shirt/55003.jpg
data/train/Sandal/55004.jpg
data/train/Bag/55005.jpg
data/train/Tshirt/55006.jpg
data/train/Coat/55007.jpg
data/train/Sneaker/55008.jpg
data/train/Bag/55009.jpg
data/train/Shirt/55010.jpg
data/train/Sneaker/55011.jpg
data/train/Tshirt/55012.jpg
data/train/Ankle boot/55013.jpg
data/train/Sneaker/55014.jpg
data/train/Dress/55015.jpg
data/train/Sandal/55016.jpg
data/train/Tshirt/55017.jpg
data/train/Shirt/55018.jpg
data/train/Tshirt/55019.jpg
data/train/Sneaker/55020.jpg
data/train/Sneaker/55021.jpg
data/train/Trouser/55022.jpg
data/train/Shirt/55023.jpg
data/train/Tshirt/55024.jpg
data/train/Ankle boot/55025.jpg
data/train/Pullover/55026.jpg
data/train/Sneaker/55027.jpg
data/train/Coat/55028.jpg
data/train/Pullover/55029.jpg
data/train/Trouser/55030.jpg
data/train/Pullover/55031.jpg
data/train/Trouser/55032.jpg
data/train/Shirt/550

In [6]:
def save_image(filename, data_array):
    im = Image.fromarray(data_array.astype('uint8'))
    im_invert = ImageOps.invert(im)
    im_invert.save(filename)

# Load Fashion-MNIST Data
(x_train, y_train), (x_test, y_test) = fashion_mnist.load_data()

DIR_NAME = "data/test/Tshirt"
if os.path.exists(DIR_NAME) == False:
    os.mkdir(DIR_NAME)
DIR_NAME = "data/test/Trouser"
if os.path.exists(DIR_NAME) == False:
    os.mkdir(DIR_NAME)
DIR_NAME = "data/test/Dress"
if os.path.exists(DIR_NAME) == False:
    os.mkdir(DIR_NAME)
DIR_NAME = "data/test/Coat"
if os.path.exists(DIR_NAME) == False:
    os.mkdir(DIR_NAME)
DIR_NAME = "data/test/Sandal"
if os.path.exists(DIR_NAME) == False:
    os.mkdir(DIR_NAME)
DIR_NAME = "data/test/Shirt"
if os.path.exists(DIR_NAME) == False:
    os.mkdir(DIR_NAME)
DIR_NAME = "data/test/Sneaker"
if os.path.exists(DIR_NAME) == False:
    os.mkdir(DIR_NAME)
DIR_NAME = "data/test/Ankle boot"    
if os.path.exists(DIR_NAME) == False:
    os.mkdir(DIR_NAME)
DIR_NAME = "data/test/Bag"  
if os.path.exists(DIR_NAME) == False:
    os.mkdir(DIR_NAME)
DIR_NAME = "data/test/Pullover"  
if os.path.exists(DIR_NAME) == False:
    os.mkdir(DIR_NAME)

# Save Images
i = 0
for li in [x_test]:
    print("[---------------------------------------------------------------]")
    for x in li:
        name = getcode(y_test[i])
        if name == "Tshirt" :
            filename = "data/test/Tshirt/{0}.jpg".format(i)
        elif name == "Trouser" :
            filename = "data/test/Trouser/{0}.jpg".format(i)
        elif name == "Dress" :
            filename = "data/test/Dress/{0}.jpg".format(i)
        elif name == "Coat" :
            filename = "data/test/Coat/{0}.jpg".format(i)
        elif name == "Sandal" :
            filename = "data/test/Sandal/{0}.jpg".format(i)
        elif name == "Shirt" :
            filename = "data/test/Shirt/{0}.jpg".format(i)
        elif name == "Sneaker" :
            filename = "data/test/Sneaker/{0}.jpg".format(i)
        elif name == "Bag" :
            filename = "data/test/Bag/{0}.jpg".format(i)
        elif name == "Ankle boot" :
            filename = "data/test/Ankle boot/{0}.jpg".format(i)
        elif name == "Pullover" :
            filename = "data/test/Pullover/{0}.jpg".format(i)
        print(filename)
        save_image(filename, x)
        i += 1

Streaming output truncated to the last 5000 lines.
data/test/Pullover/5000.jpg
data/test/Dress/5001.jpg
data/test/Shirt/5002.jpg
data/test/Coat/5003.jpg
data/test/Shirt/5004.jpg
data/test/Dress/5005.jpg
data/test/Shirt/5006.jpg
data/test/Ankle boot/5007.jpg
data/test/Coat/5008.jpg
data/test/Ankle boot/5009.jpg
data/test/Tshirt/5010.jpg
data/test/Bag/5011.jpg
data/test/Dress/5012.jpg
data/test/Sandal/5013.jpg
data/test/Shirt/5014.jpg
data/test/Pullover/5015.jpg
data/test/Tshirt/5016.jpg
data/test/Trouser/5017.jpg
data/test/Dress/5018.jpg
data/test/Ankle boot/5019.jpg
data/test/Coat/5020.jpg
data/test/Pullover/5021.jpg
data/test/Sandal/5022.jpg
data/test/Tshirt/5023.jpg
data/test/Sandal/5024.jpg
data/test/Dress/5025.jpg
data/test/Pullover/5026.jpg
data/test/Sandal/5027.jpg
data/test/Tshirt/5028.jpg
data/test/Tshirt/5029.jpg
data/test/Tshirt/5030.jpg
data/test/Tshirt/5031.jpg
data/test/Tshirt/5032.jpg
data/test/Ankle boot/5033.jpg
data/test/Trouser/5034.jpg
data/test/Dress/5035.jpg
data/t

[---------------------------------------------------------------]


IndexError: ignored

In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
get_ipython().run_line_magic('matplotlib', 'inline')
import seaborn as sns
sns.set(style="whitegrid")
import os
import glob as gb
import cv2
from scipy import misc
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
import scipy.misc
import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout
from sklearn.model_selection import train_test_split
import tensorflow as tf
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import roc_curve, auc
from matplotlib import pyplot as plt
import matplotlib.image as mpimg
from skimage import color
from skimage import io

In [8]:
trainpath = 'data/'
testpath =  'data/'

In [9]:
# Reading files [ training_dataset ] 

for folder in  os.listdir(trainpath + 'train') : 
    files = gb.glob(pathname= str( trainpath +'train//' + folder + '/*.jpg'))
    print(f'For training data , found {len(files)} in folder {folder}')

For training data , found 6000 in folder Sneaker
For training data , found 6000 in folder Pullover
For training data , found 6000 in folder Coat
For training data , found 6000 in folder Dress
For training data , found 6000 in folder Tshirt
For training data , found 6000 in folder Sandal
For training data , found 6000 in folder Ankle boot
For training data , found 6000 in folder Bag
For training data , found 6000 in folder Shirt
For training data , found 6000 in folder Trouser


In [10]:
# Reading files [ test_dataset ]

for folder in  os.listdir(testpath +'test') : 
    files = gb.glob(pathname= str( testpath +'test//' + folder + '/*.jpg'))
    print(f'For testing data , found {len(files)} in folder {folder}')

For testing data , found 1000 in folder Sneaker
For testing data , found 1000 in folder Pullover
For testing data , found 1000 in folder Coat
For testing data , found 1000 in folder Dress
For testing data , found 1000 in folder Tshirt
For testing data , found 1000 in folder Sandal
For testing data , found 1000 in folder Ankle boot
For testing data , found 1000 in folder Bag
For testing data , found 1000 in folder Shirt
For testing data , found 1000 in folder Trouser


In [13]:
# to change every_folder with label  

code = {'Tshirt':0 ,'Trouser':1,'Pullover':2,'Dress':3,'Coat':4,'Sandal':5,'Shirt':6,'Sneaker':7,'Bag':8,'Ankle boot':9}
#######################
def getcode(n) : 
    for x , y in code.items() : 
        if n == y : 
            return x

In [14]:
# to get more info about train_data  ex:[size of each pic , color , num of each size] 
size = []
for folder in  os.listdir(trainpath +'train') : 
    files = gb.glob(pathname= str( trainpath +'train//' + folder + '/*.jpg'))
    for file in files: 
        image = plt.imread(file)
        size.append(image.shape)
pd.Series(size).value_counts()

(28, 28)    60000
dtype: int64

In [15]:
# to resize images_train to one equalied size      
X_train = []
y_train = []

for folder in  os.listdir(trainpath +'train') : 
    files = gb.glob(pathname= str( trainpath +'train//' + folder + '/*.jpg'))
    for file in files: 
        image = cv2.imread(file)
        imgGray = color.rgb2gray( image)
        X_train.append(list(imgGray))
        y_train.append(code[folder])

In [16]:
# to resize images_test to one equalied size 

X_test = []
y_test = []
for folder in  os.listdir(testpath +'test') : 
    files = gb.glob(pathname= str(testpath + 'test//' + folder + '/*.jpg'))
    for file in files: 
        image = cv2.imread(file)
        imgGray = color.rgb2gray( image)
        X_test.append(list(imgGray))
        y_test.append(code[folder])

In [17]:
################# preprocessing images to arrays ####################
X_train = np.array(X_train)
X_test = np.array(X_test)
#X_pred_array = np.array(X_pred)
y_train = np.array(y_train)
y_test = np.array(y_test)

In [18]:
print(X_train)

[[[1.         1.         1.         ... 1.         1.         1.        ]
  [1.         1.         1.         ... 1.         1.         1.        ]
  [1.         1.         1.         ... 1.         1.         1.        ]
  ...
  [1.         1.         1.         ... 1.         1.         1.        ]
  [1.         1.         1.         ... 1.         1.         1.        ]
  [1.         1.         1.         ... 1.         1.         1.        ]]

 [[1.         1.         1.         ... 1.         1.         1.        ]
  [1.         1.         1.         ... 0.98431373 0.98431373 0.98431373]
  [1.         1.         1.         ... 1.         0.99215686 0.98823529]
  ...
  [1.         1.         1.         ... 0.92156863 0.94901961 0.98823529]
  [0.99607843 1.         1.         ... 1.         1.         1.        ]
  [0.98039216 0.98039216 0.98431373 ... 1.         0.99607843 0.99607843]]

 [[1.         1.         1.         ... 1.         0.94509804 0.97647059]
  [1.         1.      

In [19]:
type(X_train)

numpy.ndarray

In [20]:
print(X_train.shape)

(60000, 28, 28)


In [21]:
print(y_train)

[7 7 7 ... 1 1 1]


In [22]:
model = tf.keras.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128, activation= 'relu'),
    tf.keras.layers.Dense(10) # linear activation function
])

In [23]:
model.compile(optimizer= 'adam', 
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics = ['accuracy'])

In [24]:
import os, datetime

In [25]:
%%timeit -n1 -r1 # time required toexecute this cell once

# To view in TensorBoard
logdir = os.path.join("logs/adam", datetime.datetime.now().strftime("%Y%m%d-%H%M%S"))
tensorboard_callback = tf.keras.callbacks.TensorBoard(logdir, histogram_freq=1)

model.fit(X_train, y_train, epochs= 10, callbacks = [tensorboard_callback])

Epoch 1/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.6147 - accuracy: 0.7759
Epoch 2/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.4868 - accuracy: 0.8224
Epoch 3/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.4499 - accuracy: 0.8360
Epoch 4/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.4254 - accuracy: 0.8436
Epoch 5/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.4077 - accuracy: 0.8512
Epoch 6/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.3955 - accuracy: 0.8557
Epoch 7/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.3818 - accuracy: 0.8606
Epoch 8/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.3716 - accuracy: 0.8636
Epoch 9/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.3604 - accuracy: 0.8672
Epoch 10/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.353

In [26]:
test_loss, test_acc = model.evaluate(X_test, y_test, verbose= 2)
print(f'\nTest accuracy: {test_acc}')

313/313 - 1s - loss: 0.4061 - accuracy: 0.8550 - 885ms/epoch - 3ms/step

Test accuracy: 0.8550000190734863


In [27]:
model.save('ClothesFinal2.h5',save_format='h5')

In [28]:
X_image = []
image = cv2.imread('data/test/Bag/1014.jpg')
imgGray = color.rgb2gray(image)
image_array = cv2.resize(imgGray , (28,28))
X_image.append(list(image_array))
X_test=[]
X_test.append(list(image_array))
X_test = np.array(X_test)
y_pred = model.predict(X_test)
print(getcode(np.argmax(y_pred))) 

Bag


In [29]:
X_image = []
image = cv2.imread('data/test/Tshirt/1000.jpg')
imgGray = color.rgb2gray(image)
image_array = cv2.resize(imgGray , (28,28))
X_image.append(list(image_array))
X_test=[]
X_test.append(list(image_array))
X_test = np.array(X_test)
y_pred = model.predict(X_test)
print(getcode(np.argmax(y_pred))) 

Tshirt


In [30]:
X_image = []
image = cv2.imread('data/test/Sandal/1041.jpg')
imgGray = color.rgb2gray(image)
image_array = cv2.resize(imgGray , (28,28))
X_image.append(list(image_array))
X_test=[]
X_test.append(list(image_array))
X_test = np.array(X_test)
y_pred = model.predict(X_test)
print(getcode(np.argmax(y_pred)))

Sandal
